version: "3.3"
services:
  app:
    build: .
    links:
      - database
    ports:
      - "8080:8000"

  database:
    platform: linux/x86_64
    image: mysql:5.7
    # image: mysql:8.0.13
    container_name: "312project_db"
    ports:
      - "8000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro